Repository martin-olivier/dylib, pull requests merged in 2022-06, with the labels that each got.

#39 38 cant use a static message buffer
  include/dylib.hpp
Labels: bug

#40 HINSTANCE is no longer assigned to nullptr
  include/dylib.hpp
Labels: enhancement

#42 A bunch of changes
  .github/workflows/CI.yml
  LICENSE
  example/lib.cpp
  include/dylib.hpp
  tests/lib.cpp
  tests/tests.cpp
Labels: bug, enhancement

#44 43 update readme
  CMakeLists.txt
  README.md
  example/CMakeLists.txt
  example/README.md
  example/lib.cpp
  example/main.cpp
  tests/lib.cpp
Labels: documentation

#45 Last 2.0 changes
  LICENSE
  README.md
  example/CMakeLists.txt
  example/README.md
  include/dylib.hpp
  tests/tests.cpp
Labels: enhancement

#47 46 coverage report
  .codecov.yml
  .github/workflows/CI.yml
  .gitignore
  CMakeLists.txt
  README.md
  include/dylib.hpp
  tests/tests.cpp
Labels: enhancement

#52 feat: add_filename_decorations and no_filename_decorations constants
  README.md
  include/dylib.hpp
  tests/tests.cpp
Labels: enhancement

#53 Add std::filesystem::path support in dylib constructor
  .github/workflows/CI.yml
  CMakeLists.txt
  include/dylib.hpp
  tests/tests.cpp
Labels: enhancement

#57 Version 2.1.0
  .github/workflows/CI.yml
  CMakeLists.txt
  README.md
  example/CMakeLists.txt
  example/README.md
  include/dylib.hpp
  tests/tests.cpp
Labels: enhancement

#58 feat: new project banner
  README.md
Labels: documentation
