Repository martin-olivier/dylib, pull requests merged in 2022-05, with the labels that each got.

#15 Restructure CMakeLists.txt to be suitable for CPM.cmake
  CMakeLists.txt
Labels: bug

#19 fix: ambiguity inside documentation regarding references vs values for get_variable()
  README.md
Labels: documentation

#24 Fix test suite
  .github/workflows/CI.yml
  CMakeLists.txt
Labels: bug

#21 Changed return value type of get_function member
  README.md
  include/dylib.hpp
  tests/tests.cpp
Labels: enhancement

#34 Change API to accept names without the path and the lib prefix
  CMakeLists.txt
  include/dylib.hpp
  tests/tests.cpp
Labels: enhancement
